### ISSUE TITLE
[ERROR]: 

### ISSUE THREAD

**Issue by HASSANTECHNO** [shadow578/Yodel#10]
### Feature Description

**_### Why does this function give an error?_**  

fun download(progressCallback: (Float , Long) -> Unit , tries: Int = 1): YoutubeDLResponse? {
        var retry = tries
        check(initialized) { "youtube-dl was not initialized! call YoutubeDLWrapper.init() first!" }
        var response: YoutubeDLResponse?
        do {
            response = download(progressCallback)
            if (response != null) {
                break
            }
        } while (--retry > 0)
        return response
    }

### Acknowledgements

- [X] I have searched the existing issues and this is a **new** feature request
- [X] I have written a **informative** title
- [X] I filled out **all** the information requested in this form
- [X] I have updated to the **[latest app version](https://github.com/shadow578/Yodel/releases/latest)** and the feature is still missing

**Comment by shadow578** [comment]
Hi,
could you please elaborate where the function is located exactly? If possible, use a permalink to the line the function appears at. 

Also, could you please add what error the function throws?

**Comment by shadow578** [comment]
closing since i did not receive any update yet
