### ISSUE TITLE
[Teach]: 

### ISSUE THREAD

**Issue by HASSANTECHNO** [shadow578/Yodel#16]
### Feature Description

Can you design an in-app language switching implementation with Jetpack Compose?

### Acknowledgements

- [X] I have searched the existing issues and this is a **new** feature request
- [X] I have written a **informative** title
- [X] I filled out **all** the information requested in this form
- [X] I have updated to the **[latest app version](https://github.com/shadow578/Yodel/releases/latest)** and the feature is still missing

**Comment by shadow578** [comment]
Hi,
please use the issues only for things related to the project (like enhancements, bugs, etc.).
